export {SearchSchoolScreen} from './SearchSchoolScreen';
import PhoneAuthScreen from './PhoneAuthScreen/PhoneAuthScreen';
export {LoginScreen} from './LoginScreen';
export {SignUpScreen} from './SignUpScreen';
export {HomeScreen} from './HomeScreen';
export {CameraScreen, CameraCheckScreen, GalleryScreen} from './HomeScreen';
export {ProfileScreen, StudentList} from './ProfileScreen';
export {NoticeScreen} from './NoticeScreen';
export {SignUpSubScreen} from './SignUpSubScreen';
export {PhoneAuthScreen} from './PhoneAuthScreen';
export {TeacherScreen} from './ProfileScreen';
